language: node_js
node_js:
   - "0.10"
after_script:
   - npm run zuul
   - npm run coveralls
env:
  global:
    - secure: i8PRtvRvFRtWmeqZkXjlguwmYtjnwgzv1XhJf90x+7soJc0VJwahv2oKXgw1GUa6W/XyyPGXUuAG/woVSASQlXL4HEYxEbIbUUtBo0HovQHppiDdXxcCR2mHgbApfkFG9HAzuymYLJrW718grPs2851g34ECYYAyBmsAw2Cjvr8=
    - secure: epmU4lgIGvvF2yzaX/Bo+5xk4vlpLudE3OTVdpf2jcMWliie+7YAmaj/grIbpU6CU2/D19XUcrZGuQf1BXSvu2QyoQ5b/ETzNV4siFDuY6+eksdqugc5G357qy5fUGbDkDaI35C29AB5jRZKSCuEMLYy6EC59iM3WlceKZjABQw=